### ISSUE TITLE
Run on a different dataset

### ISSUE THREAD

**Issue by MayarOssama** [epfml/interpret-lm-knowledge#2]
Hello, 
I want to integrate your approach into my project, so how can I use it on a different dataset?
is there a certain format for the dataset?

**Comment by vinitra** [comment]
Hello @MayarOssama -- sorry for the very late reply. You can see through the [generate_df function](https://github.com/epfml/interpret-lm-knowledge/blob/6721cf2557c795a5546d9fb5fc1d85d0752633f3/scripts/run_knowledge_graph_experiments.py#L53) the three datasets that we use in the study represented as a pandas df with one row per sentence. You can simply modify this function to import your dataset with each sentence as a line in the table. Hope this helps!
